<?php
/** Emerald Central Hub V11 — dataset path registry (auto-generated by update.php) */
return array (
  'users' => 'modules/users/data/users.json',
  'login_logs' => 'modules/users/data/login_logs.json',
  'activity_logs' => 'modules/users/data/activity_logs.json',
  'notes' => 'modules/notes/data/notes.json',
  'cloaking' => 'modules/domains/data/domains.json',
  'domains' => 'modules/domains/data/domains.json',
  'file_meta' => 'modules/storage/data/file_meta.json',
  'firewall' => 'modules/firewall/data/firewall.json',
);
